name: Deploy Spring Boot API
run-name: ${{ github.actor }} deploys the application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: parcinfo
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -uroot -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: Wait for MySQL to be ready
        timeout-minutes: 3
        run: |
          for i in `seq 1 10`; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              echo "MySQL is ready"
              exit 0
            fi
            echo "MySQL not ready yet. Attempt $i/10"
            sleep 3
          done
          echo "MySQL did not start in time"
          exit 1

      - name: Initialize database schema
        run: |
          mysql -h 127.0.0.1 -u root -proot parcinfo < conception/parcinfo.sql

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Prepare artifact
        run: mkdir staging && cp target/*.jar staging

      - uses: actions/upload-artifact@v4
        with:
          name: Jar-Package
          path: staging

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Jar-Package
          path: staging

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            systemctl stop myapp.service
            cp staging/*.jar /opt/myapp/
            systemctl start myapp.service