name: Deploy Spring Boot API
run-name: ${{ github.actor }} deploys the application
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: parcinfo
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -uroot -proot"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: Wait for MySQL to be ready
        timeout-minutes: 5
        run: |
          for i in `seq 1 30`; do  # More retries
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
            echo "MySQL is ready"
            exit 0
            fi
            echo "MySQL not ready yet. Attempt $i/30"
            sleep 5
          done
          exit 1

      - name: Initialize database schema
        run: |
          mysql -h 127.0.0.1 -u root -proot parcinfo < conception/parcinfo.sql

      - name: Permission Mvnw
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: |
          ./mvnw --batch-mode verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Fhurai_ParcInfoAPI
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/parcinfo
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Prepare artifact
        run: mkdir staging && cp target/*.jar staging

      - uses: actions/upload-artifact@v4
        with:
          name: artefact
          path: staging